#!/usr/bin/php
<?php
declare(strict_types=1);

use Silver\Engine\CLI;

$CWD = str_replace('\\', '/', dirname(__FILE__));
define('ROOT', $CWD . '/');
define('DS', DIRECTORY_SEPARATOR);
define('EXT', '.php');

if (!function_exists('dd')) {
    function dd(mixed $data, bool $dump = false): never
    {
        $dump ? var_dump('<pre>', $data, '<pre>') : var_dump($data);
        exit();
    }
}

require_once ROOT . 'vendor/autoload.php';

return new CLI($argv);
