#!/usr/bin/php
<?php

/**
 * SilverEngine  - PHP MVC framework
 *
 * @package   SilverEngine
 * @author    SilverEngine Team
 * @copyright 2015-2017
 * @license   MIT
 * @link      https://github.com/SilverEngine/Framework
 */

namespace Silver;

use Silver\Engine\CLI;

/**
 * Defining framework root directory
 * and jump into it.
 */
$CWD = str_replace('\\', '/', dirname(__FILE__));
$CWD = str_replace('/System/Engine/CLI', '', $CWD);
//ltrim($CWD);
define('ROOT', $CWD . '/');

//die(ROOT);

/**
 * Defining php extension.
 */
define('EXT', '.php');

include_once(ROOT.'System/Core/Blueprints/RenderInterface'.EXT);
include_once(ROOT.'System/Engine/Ghost/Template'.EXT);

include_once('System/Engine/CLI/index.php');

return new CLI($argv);
